-- MySQL Script generated by MySQL Workbench
-- Tue Jun 18 23:22:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Work
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Work
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Work` ;
USE `Work` ;

-- -----------------------------------------------------
-- Table `Work`.`Oblast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work`.`Oblast` (
  `idOblast` INT NOT NULL,
  PRIMARY KEY (`idOblast`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Work`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work`.`City` (
  `idCity` INT NOT NULL,
  `Oblast_id` INT NULL,
  PRIMARY KEY (`idCity`),
  INDEX `Oblast_id_idx` (`Oblast_id` ASC) VISIBLE,
  CONSTRAINT `fk_Oblast_id`
    FOREIGN KEY (`Oblast_id`)
    REFERENCES `Work`.`Oblast` (`idOblast`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Work`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work`.`Users` (
  `idUsers` INT NOT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Work`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work`.`Company` (
  `idCompany` INT NOT NULL,
  `User_id` INT NULL,
  PRIMARY KEY (`idCompany`),
  INDEX `User_id_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_id`
    FOREIGN KEY (`User_id`)
    REFERENCES `Work`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Work`.`Filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work`.`Filial` (
  `idFilial` INT NOT NULL,
  `City_id` INT NULL,
  PRIMARY KEY (`idFilial`),
  INDEX `fk_City_id_idx` (`City_id` ASC) VISIBLE,
  CONSTRAINT `fk_City_id`
    FOREIGN KEY (`City_id`)
    REFERENCES `Work`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Work`.`Operators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work`.`Operators` (
  `idOperators` INT NOT NULL,
  `Filial_id` INT NULL,
  PRIMARY KEY (`idOperators`),
  INDEX `fk_Filial_id_idx` (`Filial_id` ASC) VISIBLE,
  CONSTRAINT `fk_Filial_id`
    FOREIGN KEY (`Filial_id`)
    REFERENCES `Work`.`Filial` (`idFilial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Work`.`Vacancy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work`.`Vacancy` (
  `idVacancy` INT NOT NULL,
  `Company_id` INT NULL,
  `Operator_id` INT NULL,
  `Filial_id` INT NULL,
  PRIMARY KEY (`idVacancy`),
  INDEX `Company_id_idx` (`Company_id` ASC) VISIBLE,
  INDEX `fk_Operator_id_idx` (`Operator_id` ASC) VISIBLE,
  INDEX `fk_Filial_id_idx` (`Filial_id` ASC) VISIBLE,
  CONSTRAINT `fk_Company_id`
    FOREIGN KEY (`Company_id`)
    REFERENCES `Work`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operator_id`
    FOREIGN KEY (`Operator_id`)
    REFERENCES `Work`.`Operators` (`idOperators`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filial_id`
    FOREIGN KEY (`Filial_id`)
    REFERENCES `Work`.`Filial` (`idFilial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Work`.`Resume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Work`.`Resume` (
  `idResume` INT NOT NULL,
  `City_id` INT NULL,
  `Filial_id` INT NULL,
  `Operator_id` INT NULL,
  `User_id` INT NULL,
  PRIMARY KEY (`idResume`),
  INDEX `fk_City_id_idx` (`City_id` ASC) VISIBLE,
  INDEX `fk_Filial_id_idx` (`Filial_id` ASC) VISIBLE,
  INDEX `fk_Operator_id_idx` (`Operator_id` ASC) VISIBLE,
  INDEX `fk_User_id_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_City_id`
    FOREIGN KEY (`City_id`)
    REFERENCES `Work`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filial_id`
    FOREIGN KEY (`Filial_id`)
    REFERENCES `Work`.`Filial` (`idFilial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operator_id`
    FOREIGN KEY (`Operator_id`)
    REFERENCES `Work`.`Operators` (`idOperators`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_id`
    FOREIGN KEY (`User_id`)
    REFERENCES `Work`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
